---
- name: "install initscripts fontconfig"
  yum:
   name: "{{item}}"
   state: present
  with_items:
  - initscripts
  - fontconfig

- name: "download and install the grafana rpm"
  yum:
   name: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.0.1-1.x86_64.rpm
   state: present

- name: "start grafana"
  service:
   name: grafana-server
   state: started
   enable: yes

